const products = [
  {
    _id: "1",
    name: "Airpods wireless Bluetooth Headphones",
    image: "/images/bottle-01.jpg",
    description:
      "Bluetooth technology lets you connect it with compatible wirelessly High-quality audio",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 0,
    rating: 4.5,
    numReviews: 16,
  },
  {
    _id: "2",
    name: "Airpods wireless Bluetooth Headphones",
    image: "/images/bottle-02.jpg",
    description:
      "Bluetooth technology lets you connect it with compatible wirelessly High-quality audio",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 16,
  },
  {
    _id: "3",
    name: "Airpods wireless Bluetooth Headphones",
    image: "/images/bottle-03.jpg",
    description:
      "Bluetooth technology lets you connect it with compatible wirelessly High-quality audio",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 16,
  },
  {
    _id: "4",
    name: "Airpods wireless Bluetooth Headphones",
    image: "/images/iphone-01.jpg",
    description:
      "Bluetooth technology lets you connect it with compatible wirelessly High-quality audio",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 16,
  },
  {
    _id: "5",
    name: "Airpods wireless Bluetooth Headphones",
    image: "/images/iphone-02.jpg",
    description:
      "Bluetooth technology lets you connect it with compatible wirelessly High-quality audio",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 16,
  },
  {
    _id: "6",
    name: "Airpods wireless Bluetooth Headphones",
    image: "/images/iphone-03.jpg",
    description:
      "Bluetooth technology lets you connect it with compatible wirelessly High-quality audio",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 16,
  },
];
export default products;
